package software.uncharted.terarium.hmiserver.models.dataservice.equation;

import com.fasterxml.jackson.annotation.JsonAlias;
import lombok.Data;
import lombok.experimental.Accessors;
import software.uncharted.terarium.hmiserver.annotations.TSModel;
import software.uncharted.terarium.hmiserver.annotations.TSOptional;

/** Equation Source Data Model */
@TSModel
@Data
@Accessors(chain = true)
public class EquationSource {

  /** The document id of the source for the equation * */
  @JsonAlias("extracted_from")
  @TSOptional
  private String extractedFrom;

  /** The file name of the asset that represents the source for the equation* */
  @JsonAlias("document_asset_name")
  @TSOptional
  private String documentAssetName;

  /** Whether the equation was generated by the HMI * */
  @JsonAlias("hmi_generated")
  @TSOptional
  private Boolean hmiGenerated;
}
