---
services:
    pyciemss-api:
        container_name: pyciemss-api
        image: ghcr.io/darpa-askem/pyciemss-api:latest
        networks:
            - terarium
        environment:
            PYCIEMSS_OUTPUT_FILEPATH: "result.csv"
            RABBITMQ_HOST: "rabbitmq"
            RABBITMQ_PASSWORD: "terarium123"
            RABBITMQ_PORT: "5672"
            RABBITMQ_SSL: "False"
            RABBITMQ_USERNAME: "terarium"
            REDIS_HOST: "redis"
            REDIS_PORT: "6379"
            STANDALONE_MODE: "False"
            TDS_PASSWORD: "service123"
            TDS_URL: "http://hmi-server:3000"
            TDS_USER: "api-service"
        depends_on:
            redis:
                condition: service_started
        extra_hosts:
            - "${local_host_name}:host-gateway"

    pyciemss-worker:
        container_name: pyciemss-worker
        image: ghcr.io/darpa-askem/pyciemss-worker:latest
        networks:
            - terarium
        environment:
            PYCIEMSS_OUTPUT_FILEPATH: "result.csv"
            RABBITMQ_HOST: "rabbitmq"
            RABBITMQ_PASSWORD: "terarium123"
            RABBITMQ_PORT: "5672"
            RABBITMQ_SSL: "False"
            RABBITMQ_USERNAME: "terarium"
            REDIS_HOST: "redis"
            REDIS_PORT: "6379"
            STANDALONE_MODE: "False"
            TDS_PASSWORD: "service123"
            TDS_URL: "http://hmi-server:3000"
            TDS_USER: "api-service"
        depends_on:
            redis:
                condition: service_started
        extra_hosts:
            - "${local_host_name}:host-gateway"
