---
enableGlobalCache: true

nodeLinker: node-modules

plugins:
  # Used for `yarn workspaces focus`
  # and `yarn workspaces foreach`
  # https://github.com/yarnpkg/berry/blob/HEAD/packages/plugin-workspace-tools/README.md
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
