---
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - terarium
    ports:
      - '6379:6379'
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: '3s'
      timeout: '3s'
      retries: 30

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    networks:
      - terarium
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "pantera" ]
      interval: "3s"
      timeout: "3s"
      retries: 30
    user: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - terarium-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  terarium-db:
    driver: local
