---
version: '3.8'

services:
  redis:
    image: ghcr.io/darpa-askem/redis:7.0.12-alpine
    container_name: redis
    networks:
      - terarium
    ports:
      - '6379:6379'
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: '3s'
      timeout: '3s'
      retries: 30
  postgres:
    image: ghcr.io/darpa-askem/postgres:15.1
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "terarium"
    networks:
      - terarium
    ports:
      - '5430:5432'
    restart: always
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: '3s'
      timeout: '3s'
      retries: 30

networks:
  terarium:
    name: terarium
