---
version: "3.8"

include:
  - scripts/docker-compose-base.yml
  - scripts/docker-compose-common.yml
  - scripts/docker-compose-keycloak.yml

services:
  hmi-server:
    image: ghcr.io/darpa-askem/hmi-server:lean-test
    container_name: hmi-server
    networks:
      - terarium
    ports:
      - "3000:3000"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--head",
          "0.0.0.0:3000/actuator/health"
        ]
      interval: "3s"
      timeout: "3s"
      retries: 30
    environment:
      ADOBE_API-KEY: ""
      GOOGLE-ANALYTICS-ID: ""
      AWS_URL: "http://minio:9000"
      AWS_ACCESS_KEY_ID: "admin"
      AWS_SECRET_ACCESS_KEY: "admin123"
      SPICEDB_LAUNCHMODE: "PLAINTEXT"
      SPICEDB_SHARED-KEY: "dev"
      SPICEDB_TARGET: "spicedb:50051"
      SPRING_DATA_REDIS_URL: "redis://redis:6379"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/terarium"
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI: "http://keycloak:8081/realms/Terarium"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT-ID: "app"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: "http://keycloak:8081/realms/Terarium"
      TERARIUM_DB_PASSWORD: "postgres"
      TERARIUM_DB_USERNAME: "postgres"
      TERARIUM_KEYCLOAK_URL: "http://keycloak:8081"
      TERARIUM_KEYCLOAK_REALM: "Terarium"
      TERARIUM_KEYCLOAK_CLIENT-ID: "app"
      TERARIUM_KEYCLOAK_ADMIN-REALM: "master"
      TERARIUM_KEYCLOAK_ADMIN-CLIENT-ID: "admin-cli"
      TERARIUM_KEYCLOAK_ADMIN-USERNAME: "admin"
      TERARIUM_KEYCLOAK_ADMIN-PASSWORD: "admin123"
      TERARIUM_MQ-ADDRESSES: "amqp://rabbitmq:5672"
      TERARIUM_MQ-HOST: "rabbitmq"
      TERARIUM_MQ-PASSWORD: "terarium123"
      TERARIUM_MQ-POST: "5672"
      TERARIUM_MQ-USERNAME: "terarium"
      TERARIUM_ELASTICSEARCH_URL: "http://elasticsearch:9200"
      TERARIUM_ELASTICSEARCH_AUTH-ENABLED: false
      SPRING_NEO4J_URI: "bolt://neo4j:7687"
      SPRING_NEO4J_AUTHENTICATION_USERNAME: "neo4j"
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: "password"
      TGPT_APP_URL: ""
      TGPT_TOKEN: ""
      TGPT_WS_URL: ""
      XDD_API-ES-KEY: ""
      XDD_API-KEY: ""
    depends_on:
      postgres:
        condition: service_healthy
      spicedb:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  elasticsearch-data:
  minio-data:
  terarium-db:
    driver: local

networks:
  terarium:
    name: terarium
