---
version: '3.8'
services:
  grafana:
    image: ghcr.io/unchartedsoftware/uncharted-shipyard/uncharted-grafana:10.0.3
    ports:
      - 8096:3000
    extra_hosts:
      - "${local_host_name}:host-gateway"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./dashboards:/var/lib/grafana/dashboards
      - ./provisioning/datasources/terarium.yaml:/etc/grafana/provisioning/datasources/terarium.yaml
      - ./provisioning/dashboards/terarium.yaml:/etc/grafana/provisioning/dashboards/terarium.yaml

  loki:
    image: ghcr.io/unchartedsoftware/uncharted-shipyard/uncharted-loki:2.8.11
    ports:
      - 3100:3100
    extra_hosts:
      - "${local_host_name}:host-gateway"

  prometheus:
    image: ghcr.io/unchartedsoftware/uncharted-shipyard/uncharted-prometheus:v2.45.0
    ports:
      - 9091:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    extra_hosts:
      - "${local_host_name}:host-gateway"
