apiVersion: v1
kind: Pod
metadata:
  labels:
    software.uncharted.terarium: gateway-keycloak
  name: gateway-keycloak
spec:
  containers:
    - image: docker.uncharted.software/auth/keycloak:dev-1.1.0
      name: gateway-keycloak
      args:
        - start-dev
        - --hostname=localhost
        - --hostname-port=8079
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: PROXY_ADDRESS_FORWARDING
          value: '"true"'
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: openidctest
        - name: KC_DB_URL_HOST
          value: gateway-postgres
      resources: {}
  initContainers:
    - image: docker.uncharted.software/auth/keycloak:dev-1.1.0
      name: init-gateway-keycloak
      args:
        - import
        - --dir
        - /data
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: PROXY_ADDRESS_FORWARDING
          value: '"true"'
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: openidctest
        - name: KC_DB_URL_HOST
          value: gateway-postgres
      volumeMounts:
        - name: realm-volume
          mountPath: /data
      resources: {}
  restartPolicy: Always
  volumes:
    - name: realm-volume
      configMap:
        name: gateway-keycloak-realm
status: {}
