---
version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - terarium
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: "3s"
      timeout: "3s"
      retries: 30

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    networks:
      - terarium
    ports:
      - "5430:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "pantera" ]
      interval: "3s"
      timeout: "3s"
      retries: 30
    user: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - terarium-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  reverse-proxy:
    image: ghcr.io/darpa-askem/reverse-proxy:dev_test
    container_name: reverse-proxy
    networks:
      - terarium
    ports:
      - "8888:80"
      - "443:443"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "--head", "0.0.0.0:80/healthcheck" ]
      interval: "3s"
      timeout: "3s"
      retries: 30

volumes:
  terarium-db:
    driver: local
