---
version: "3.8"

services:
  beaker:
    container_name: beaker
    image: ghcr.io/darpa-askem/beaker-kernel:latest
    networks:
      - terarium
    ports:
      - "3050:8888"
    environment:
      DATA_SERVICE_URL: "http://${local_host_name}:3000"
      JUPYTER_SERVER: "http://${local_host_name}:3050"
      SIMULATION_SCHEDULER_URL: "http://${local_host_name}:3030"
      JUPYTER_TOKEN: "89f73481102c46c0bc13b2998f9a4fce"
      TDS_USER: "${secret_service_account_username}"
      TDS_PASSWORD: "${secret_service_account_password}"

  knowledge-middleware-api:
    container_name: knowledge-middleware-api
    image: ghcr.io/darpa-askem/knowledge-middleware-api:latest
    networks:
      - terarium
    ports:
      - "3060:8000"
    environment:
      TDS_URL: "http://${local_host_name}:3000"
      SKEMA_RS_URL: "https://skema-rs.staging.terarium.ai"
      SKEMA_TR_URL: "https://skema-tr.staging.terarium.ai"
      MIT_TR_URL: "https://mit-tr.staging.terarium.ai"
      TA1_UNIFIED_URL: "https://skema-unified.staging.terarium.ai"
      OPENAI_API_KEY: "${secret_mit_openai_key}"
      TDS_USER: "${secret_service_account_username}"
      TDS_PASSWORD: "${secret_service_account_password}"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"

  knowledge-middleware-worker:
    container_name: knowledge-middleware-worker
    image: ghcr.io/darpa-askem/knowledge-middleware-worker:latest
    networks:
      - terarium
    environment:
      TDS_URL: "http://${local_host_name}:3000"
      SKEMA_RS_URL: "https://skema-rs.staging.terarium.ai"
      SKEMA_TR_URL: "https://skema-tr.staging.terarium.ai"
      MIT_TR_URL: "https://mit-tr.staging.terarium.ai"
      TA1_UNIFIED_URL: "https://skema-unified.staging.terarium.ai"
      OPENAI_API_KEY: "${secret_mit_openai_key}"
      TDS_USER: "${secret_service_account_username}"
      TDS_PASSWORD: "${secret_service_account_password}"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      redis:
        condition: service_started
