---
services:
    gollm-taskrunner:
        build:
            dockerfile: ./packages/gollm/Dockerfile
            target: gollm_taskrunner_builder
        container_name: gollm-taskrunner
        image: ghcr.io/darpa-askem/gollm-taskrunner:latest
        networks:
            - terarium
        environment:
            TERARIUM_MQ_ADDRESSES: "amqp://rabbitmq:5672"
            TERARIUM_MQ_PASSWORD: "terarium123"
            TERARIUM_MQ_USERNAME: "terarium"
            TERARIUM_TASKRUNNER_REQUEST_TYPE: "gollm"
            OPENAI_API_KEY: "${secret_gollm_openai_key}"
        depends_on:
            rabbitmq:
                condition: service_healthy
        extra_hosts:
            - "${local_host_name}:host-gateway"
        volumes:
            - ../../packages/gollm:/gollm_task
            - ../../packages/taskrunner:/taskrunner
        command: /gollm_task/dev.sh

    mira-taskrunner:
        container_name: mira-taskrunner
        image: ghcr.io/darpa-askem/mira-taskrunner:latest
        networks:
            - terarium
        environment:
            TERARIUM_MQ_ADDRESSES: "amqp://rabbitmq:5672"
            TERARIUM_MQ_PASSWORD: "terarium123"
            TERARIUM_MQ_USERNAME: "terarium"
            TERARIUM_TASKRUNNER_REQUEST_TYPE: "mira"
        depends_on:
            rabbitmq:
                condition: service_healthy
        extra_hosts:
            - "${local_host_name}:host-gateway"

    funman-taskrunner:
        container_name: funman-taskrunner
        image: ghcr.io/darpa-askem/funman-taskrunner:latest
        networks:
            - terarium
        environment:
            TERARIUM_MQ_ADDRESSES: "amqp://rabbitmq:5672"
            TERARIUM_MQ_PASSWORD: "terarium123"
            TERARIUM_MQ_USERNAME: "terarium"
            TERARIUM_TASKRUNNER_REQUEST_TYPE: "funman"
        depends_on:
            rabbitmq:
                condition: service_healthy
        extra_hosts:
            - "${local_host_name}:host-gateway"
