---
version: "3.8"

services:
  hmi-client:
    image: ghcr.io/darpa-askem/hmi-client:dev_test
    container_name: hmi-client
    networks:
      - terarium
    ports:
      - "8080:80"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--head", "0.0.0.0:80/healthcheck"]
      interval: "3s"
      timeout: "3s"
      retries: 30
