---
version: "3.9"

services:
  model-service:
    container_name: model-service
    image: ghcr.io/darpa-askem/model-service:latest
    networks:
      - terarium
    ports:
      - "3010:8888"
    extra_hosts:
      - "host.docker.internal:host-gateway"
