---
version: "3.9"

services:
    gollm-taskrunner:
        container_name: gollm-taskrunner
        image: ghcr.io/darpa-askem/gollm-taskrunner:latest
        networks:
            - terarium
        environment:
            TERARIUM_MQ-ADDRESSES: "amqp://rabbitmq:5672"
            TERARIUM_MQ-PASSWORD: "terarium123"
            TERARIUM_MQ-USERNAME: "terarium"
            OPENAI_API_KEY: "${secret_gollm_openai_key}"
            TERARIUM_TASKRUNNER_REQUEST-TYPE: "gollm"
        depends_on:
            rabbitmq:
                condition: service_healthy
        extra_hosts:
            - "host.docker.internal:host-gateway"

    mirac-taskrunner:
        container_name: mirac-taskrunner
        image: ghcr.io/darpa-askem/mirac-taskrunner:latest
        networks:
            - terarium
        environment:
            TERARIUM_MQ-ADDRESSES: "amqp://rabbitmq:5672"
            TERARIUM_MQ-PASSWORD: "terarium123"
            TERARIUM_MQ-USERNAME: "terarium"
            TERARIUM_TASKRUNNER_REQUEST-TYPE: "mirac"
        depends_on:
            rabbitmq:
                condition: service_healthy
        volumes:
            - ../../packages/taskrunner/tasks/mirac:/MiraC
        extra_hosts:
            - "host.docker.internal:host-gateway"
