---
version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - terarium
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: "3s"
      timeout: "3s"
      retries: 30

networks:
  terarium:
    name: terarium
