---
version: "3.8"

services:
  sciml-service:
    container_name: sciml-service
    image: ghcr.io/darpa-askem/sciml-service:tds-migration
    platform: linux/amd64
    networks:
      - terarium
    ports:
      - "3030:8080"
    environment:
      SIMSERVICE_TDS_URL: "http://${local_host_name}:3000"
      SIMSERVICE_USERNAME: "${secret_service_account_username}"
      SIMSERVICE_PASSWORD: "${secret_service_account_password}"
      SIMSERVICE_RABBITMQ_ENABLED: "false"
      SIMSERVICE_RABBITMQ_LOGIN: "terarium"
      SIMSERVICE_RABBITMQ_PASSWORD: "terarium123"
      SIMSERVICE_RABBITMQ_ROUTE: "sciml-queue"
      SIMSERVICE_RABBITMQ_HOST: "rabbitmq"
      SIMSERVICE_RABBITMQ_PORT: "5672"
      SIMSERVICE_RABBITMQ_SSL: "false"
    depends_on:
      rabbitmq:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pyciemss-api:
    container_name: pyciemss-api
    image: ghcr.io/darpa-askem/pyciemss-api:tds-migration
    networks:
      - terarium
    ports:
      - "3040:8000"
    environment:
      TDS_URL: "http://${local_host_name}:3000"
      TDS_USER: "${secret_service_account_username}"
      TDS_PASSWORD: "${secret_service_account_password}"
      STANDALONE_MODE: "False"
      PYCIEMSS_OUTPUT_FILEPATH: "result.csv"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      redis:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pyciemss-worker:
    container_name: pyciemss-worker
    image: ghcr.io/darpa-askem/pyciemss-worker:tds-migration
    networks:
      - terarium
    environment:
      TDS_URL: "http://${local_host_name}:3000"
      TDS_USER: "${secret_service_account_username}"
      TDS_PASSWORD: "${secret_service_account_password}"
      STANDALONE_MODE: "False"
      PYCIEMSS_OUTPUT_FILEPATH: "result.csv"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      redis:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
