---
services:
  beaker:
    container_name: beaker
    image: ghcr.io/darpa-askem/beaker-kernel:local
    networks:
      - terarium
    ports:
      - "3050:8888"
    environment:
      HMI_SERVER_URL: "http://${local_host_name}:3000"
      JUPYTER_SERVER: "http://${local_host_name}:3050"
      MIRA_REST_URL: "http://34.230.33.149:8771/"
      SIMULATION_SCHEDULER_URL: "http://${local_host_name}:3030"
      JUPYTER_TOKEN: "89f73481102c46c0bc13b2998f9a4fce"
      AUTH_USERNAME: "${secret_service_account_username}"
      AUTH_PASSWORD: "${secret_service_account_password}"
      OPENAI_API_KEY: "${secret_openai_key}"
    extra_hosts:
      - "${local_host_name}:host-gateway"
