---
services:
  gollm-taskrunner:
    build:
      context: ../..
      dockerfile: ./packages/gollm/Dockerfile
      target: gollm_taskrunner_builder
    container_name: gollm-taskrunner
    networks:
      - terarium
    environment:
      TERARIUM_MQ_ADDRESSES: "amqp://rabbitmq:5672"
      TERARIUM_MQ_PASSWORD: "terarium123"
      TERARIUM_MQ_USERNAME: "terarium"
      TERARIUM_TASKRUNNER_REQUEST_TYPE: "gollm"
      OPENAI_API_KEY: "${secret_openai_key}"
    depends_on:
      rabbitmq:
        condition: service_healthy
    extra_hosts:
      - "${local_host_name}:host-gateway"
    volumes:
      - ../../packages/gollm:/gollm_task
      - ../../packages/taskrunner:/taskrunner
    command: /gollm_task/dev.sh

  mira-taskrunner:
    build:
      context: ../..
      dockerfile: ./packages/mira/Dockerfile
      target: mira_taskrunner_builder
    container_name: mira-taskrunner
    networks:
      - terarium
    environment:
      TERARIUM_MQ_ADDRESSES: "amqp://rabbitmq:5672"
      TERARIUM_MQ_PASSWORD: "terarium123"
      TERARIUM_MQ_USERNAME: "terarium"
      TERARIUM_TASKRUNNER_REQUEST_TYPE: "mira"
    depends_on:
      rabbitmq:
        condition: service_healthy
    extra_hosts:
      - "${local_host_name}:host-gateway"
    volumes:
      - ../../packages/mira:/mira_task
      - ../../packages/taskrunner:/taskrunner
    command: /mira_task/dev.sh

  funman-taskrunner:
    build:
      context: ../..
      dockerfile: ./packages/funman/Dockerfile
      target: funman_taskrunner_builder
    container_name: funman-taskrunner
    networks:
      - terarium
    environment:
      TERARIUM_MQ_ADDRESSES: "amqp://rabbitmq:5672"
      TERARIUM_MQ_PASSWORD: "terarium123"
      TERARIUM_MQ_USERNAME: "terarium"
      TERARIUM_TASKRUNNER_REQUEST_TYPE: "funman"
    depends_on:
      rabbitmq:
        condition: service_healthy
    extra_hosts:
      - "${local_host_name}:host-gateway"
    volumes:
      - ../../packages/funman:/funman_task
      - ../../packages/taskrunner:/taskrunner
    command: /funman_task/dev.sh

  nougat_cpu-taskrunner:
    build:
      context: ../..
      dockerfile: ./packages/nougat_cpu/Dockerfile
      target: nougat_cpu_taskrunner_builder
    container_name: nougat_cpu-taskrunner
    networks:
      - terarium
    environment:
      TERARIUM_MQ_ADDRESSES: "amqp://rabbitmq:5672"
      TERARIUM_MQ_PASSWORD: "terarium123"
      TERARIUM_MQ_USERNAME: "terarium"
      TERARIUM_TASKRUNNER_REQUEST_TYPE: "nougat_cpu"
      OPENAI_API_KEY: "${secret_openai_key}"
    depends_on:
      rabbitmq:
        condition: service_healthy
    extra_hosts:
      - "${local_host_name}:host-gateway"
    volumes:
      - ../../packages/nougat_cpu:/nougat_task
      - ../../packages/taskrunner:/taskrunner
    command: /nougat_task/dev.sh
