---
version: "3.8"

services:
  gollm-taskrunner:
    container_name: gollm-taskrunner
    image: ghcr.io/darpa-askem/taskrunner:latest
    networks:
      - terarium
    environment:
      TERARIUM_MQ-ADDRESSES: "amqp://rabbitmq:5672"
      TERARIUM_MQ-PASSWORD: "terarium123"
      TERARIUM_MQ-USERNAME: "terarium"
      OPENAI_API_KEY: "${secret_gollm_openai_key}"
    depends_on:
      rabbitmq:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
