package software.uncharted.terarium.hmiserver.models;

public enum ClientEventType {
	HEARTBEAT,
	NOTIFICATION,
	SIMULATION_SCIML,
	SIMULATION_PYCIEMSS,
	SIMULATION_NOTIFICATION,
	FILE_UPLOAD_PROGRESS,
	EXTRACTION,
	EXTRACTION_PDF,
	// Events for the task runner notifications
	TASK_UNDEFINED_EVENT,
	TASK_GOLLM_MODEL_CARD,
	TASK_GOLLM_CONFIGURE_MODEL,
	TASK_GOLLM_CONFIGURE_FROM_DATASET,
	TASK_GOLLM_COMPARE_MODEL,
	TASK_GOLLM_GENERATE_SUMMARY,
	TASK_FUNMAN_VALIDATION,
	TASK_ENRICH_AMR
}
