package software.uncharted.terarium.hmiserver.models;

public enum ClientEventType {
	HEARTBEAT,
	NOTIFICATION,
	SIMULATION_SCIML,
	SIMULATION_PYCIEMSS,
	FILE_UPLOAD_PROGRESS,
	EXTRACTION,
	EXTRACTION_PDF,
	// Events for the task runner notifications
	TASK_UNDEFINED_EVENT,
	TASK_GOLLM_MODEL_CARD,
	TASK_GOLLM_CONFIGURE_MODEL,
	TASK_GOLLM_DATASET_CONFIGURE,
	TASK_GOLLM_COMPARE_MODEL,
}
