FROM alpine:3.16

LABEL org.opencontainers.image.title="TERArium Keycloak Theme"
LABEL org.opencontainers.image.description="Custom TERArium theme for Keycloak authentication"
LABEL org.opencontainers.image.licenses=Apache-2.0
LABEL org.opencontainers.image.documentation=https://github.com/DARPA-ASKEM/TERArium/tree/terrarium-login-skin/keycloak-theme

WORKDIR /terarium

COPY terarium .
