########################################################################################################################
# HMI-Server configuration
########################################################################################################################
terarium.hmiserver.url=http://hmi-server:8080
