# Automatically adds or removes labels from issues. Can be expanded to
# auto label cards and PRs as well. Issue templates are

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Determine Label
        run: |
          if [[ ${{ github.event.issue.title }} =~ ^\[FEAT\]: ]]; then
            echo "LABEL=feature" >> $GITHUB_ENV
          elif [[ ${{ github.event.issue.title }} =~ ^\[TASK\]: ]]; then
            echo "LABEL=task" >> $GITHUB_ENV
          else
            echo "LABEL=" >> $GITHUB_ENV
          fi
      - name: Label issues
        uses: andymckay/labeler@3a4296e9dcdf9576b0456050db78cfd34853f260
        with:
          add-labels: '${{ env.LABEL }}'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-if-labeled: true
