---
name: Pull Request Checklist

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
  issue_comment:
    types:
      - edited

jobs:
  comment:
    name: Pull Request Checklist
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            // Check if the bot has already approved the PR
            const {data: reviews} = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.number,
            });
            if (reviews.find(review => review.user.id === 41898282 && review.state === 'APPROVED')) {
              console.log('The PR has already been approved by the bot.');
              return;
            }

            // Find any comment already made by the bot.
            const {data: comments} = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
            })
            const botComment = comments.find(comment => comment.user.id === 41898282)

            // Create a new comment if the bot hasn't commented yet
            if (!botComment) {
              console.log("No bot comment found. Creating a new comment.");
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.number,
                body: "**Please review the checklist** \n\n- [ ] _manual test_ and/or _scenario test_ updated, if not sure ask #askem-testing\n- [ ] _documentation_ updated\n- [ ] _breaking change_ notify #askem-engineering",
              })
              return;
            }

            // Approve PR if all checklist items are checked
            if (!botComment.body.match(/- \[ \]/g)) {
              console.log("All checklist items are checked. Approving the pull request.");

              // Update the bot comment with the approved message.
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: botComment.body + "\n\nAll checklist items are checked. Approving the pull request.",
              })

              // All checklist items are checked, approve the pull request
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.number,
                event: 'APPROVE',
                body: 'All checklist items are checked',
              });
            }
