---
name: Pull Request Checklist

# yamllint disable-line rule:truthy
on:
  issue_comment:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

jobs:
  comment:
    name: Pull Request Checklist
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            // Find any comment already made by the bot.
            const {data: comments} = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
            })
            const botComment = comments.find(comment => comment.user.id === 41898282)

            // Create a new comment if the bot hasn't commented yet
            if (!botComment) {
              console.log("No bot comment found. Creating a new comment.");
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.number,
                body: "**Please review the checklist**\n- [ ] server error messages use `messages.properties`\n- [ ] _manual test_ and/or _scenario test_ updated, if not sure ask #askem-testing\n- [ ] _documentation_ updated\n- [ ] _breaking change_ notify #askem-engineering",
              })
              return;
            }

            console.log("Bot comment found.");

            // If all checklist items are checked
            if (!botComment.body.match(/- \[ \]/g)) {
              console.log("All checklist items are checked.");

              // Check if the comment has already been updated
              if (botComment.body.includes("All checklist items are checked.")) {
                console.log("Bot comment already updated.");
                return;
              }

              // Update the bot comment with the approved message.
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: botComment.body + "\n\nAll checklist items are checked.",
              })

              return;
            }

            console.log("Not all checklist items are checked.");
