---
# For debugging purposes only

name: Debug Workflow
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  BAKE_FILE: docker-bake.hcl

jobs:
  # Generate a matrix based on all the targets defined in the
  # bake file.
  targets:
    name: Generate targets list from provided bake file
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.targets.outputs.matrix }}
    steps:
      # 1.1 - checkout the files
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      # 1.2 - Generate a matrix output of all the targets for the specified group
      # if its not triggered by tag use `staging` bake group instead
      - name: Create matrix
        id: targets
        run: |
          set -x
          docker verrsion
          docker buildx version
          if [[ '${{ github.ref_type }}' == 'branch' && '${{ github.ref_name }}' == 'main' ]]; then
            BAKE_GROUP=staging
          else
            BAKE_GROUP=prod
          fi
          echo $BAKE_GROUP
          docker buildx bake $BAKE_GROUP -f ${{ env.BAKE_FILE }} --print
          echo "matrix=$(docker buildx bake $BAKE_GROUP -f ${{ env.BAKE_FILE }} --print | jq -cr '.group.default.targets')" >> $GITHUB_OUTPUT

      # 1.3 (optional) - output the generated target list for verification
      - name: Show matrix
        run: |
          echo ${{ steps.targets.outputs.matrix }}
