# Automatically build Docker images on changes to main and push them to the GitHub Container Registry

name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ['main']

jobs:
  build-push:
    name: Buid and push Docker image to GitHub Container registry
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Terarium Keycloak Theme Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./keycloak-theme/Dockerfile
          target: final
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/terarium-theme:latest
