---
# This workflow will run Spotless with Java configuration to format the Java codebase
name: Format Server
# yamllint disable-line rule:truthy
on:
  workflow_call:
  push:
    paths:
      - 'packages/server/**'
    branches: [ 'main' ]
  pull_request:
    paths:
      - 'packages/server/**'
    branches: [ 'main' ]

jobs:
  formatServer:
    name: Format Server
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      # Debugging purposes to verify branch being worked on
      - run: git branch

      # Validate Gradle JAR
      - name: Validate GradleW JAR
        uses: gradle/wrapper-validation-action@b231772637bb498f11fdbc86052b6e8a8dc9fc92

      # Setup Java 17
      - name: Setup Java v17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      # Run the formatter
      - name: Run Spotless
        uses: gradle/gradle-build-action@bdf99f9dada2506e990bac6de8ec5e3de34a04f1
        with:
          gradle-version: wrapper
          build-root-directory: packages/server
          arguments: |
            spotlessApply

      # Commit changes, only if there are changes
      - name: Commit changes
        if: steps.formatServer.outputs.exitCode == 0
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: format server codebase"
          git push
