---
# Automatically adds issues to the Integration Github project
# if the issue is tagged with `integration`

name: Add integration tasks to Integration project

on:
  issues:
    types:
      - reopened
      - opened
      - labeled
      - edited

jobs:
  add-to-project:
    name: Add integration issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@5ba1147d0e730433604387e30a57a6079f51a893
        with:
          project-url: https://github.com/orgs/DARPA-ASKEM/projects/5
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: integration
          label-operator: OR
