---
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests using node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Lint & Test
on:
  workflow_call:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.8.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.8.0
          cache: 'yarn'

      - name: Install packages
        run: yarn install --immutable

      - name: Run Linter
        run: yarn lint:ci

      - name: Run Formatter
        run: yarn prettier:ci

      - name: Run Unit Tests
        run: yarn test

  lintYaml:
    name: Lint YAML Files
    uses: darpa-askem/orchestration/.github/workflows/lint-yaml.yml@80334cf4e4a217d9ce5776b91f6d44219b218302
    with:
      strict: false

  # lintDocker:
  #   name: Lint Docker Files
  #   uses: darpa-askem/orchestration/.github/workflows/lint-docker.yml@80334cf4e4a217d9ce5776b91f6d44219b218302

  lintDocker:
    name: Lint Docker Files
    runs-on: ubuntu-22.04
    env:
      HADOLINT_RECURSIVE: true

    steps:
      # 1 - checkout the request
      - uses: actions/checkout@v3

      # 2 - lint all dockerfiles found
      - name: Lint Dockerfiles
        id: hadolint
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: Dockerfile
          recursive: true
          failure-threshold: 'error'
