---
# This workflow will run Spotless with Java configuration to format the Java codebase
name: Lint Server
# yamllint disable-line rule:truthy
on:
  workflow_call:

jobs:
  lintServer:
    name: Lint Server
    runs-on: ubuntu-22.04

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java v21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
          cache: gradle

      - name: Run Spotless
        run: |
          ./gradlew spotlessApply

      - name: Commit all changed files
        run: |
          git diff --exit-code || {
            echo "Files have changed. Committing changes..."
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git fetch --depth=1;
            git checkout  ${{ github.head_ref }} --
            git add .
            git commit --message "chore: lint and format server codebase"
            git push --set-upstream origin ${{ github.head_ref }}
          }
