---
# This workflow will do a clean installation of node dependencies, and perform the following tests
# - lint
# - format
# - typecheck
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Lint & Format Client
# yamllint disable-line rule:truthy
on:
  workflow_call:
  push:
    paths:
      - 'packages/client/**'
    branches: ['main']
  pull_request:
    paths:
      - 'packages/client/**'
    branches: ['main']

jobs:
  lintClient:
    name: Lint & Format Client
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      # Debugging purposes to verify branch being worked on
      - run: git branch

      - name: Use Node.js 18.8.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.8.0
          cache: 'yarn'

      - name: Install packages
        run: yarn install --immutable

      - name: Run Linter
        run: yarn lint:ci

      - name: Run Formatter
        run: yarn prettier:ci

      - name: Run Typechecks
        run: yarn typecheck
