---
# This workflow will run Spotless with Java configuration to format the Java codebase
name: Lint Server
# yamllint disable-line rule:truthy
on:
  workflow_call:
  push:
    paths:
      - 'packages/server/**'
    branches: [ 'main' ]
  pull_request:
    paths:
      - 'packages/server/**'
    branches: [ 'main' ]

jobs:
  lintServer:
    name: Lint Server
    runs-on: ubuntu-22.04

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java v17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Run Spotless
        uses: gradle/gradle-build-action@bdf99f9dada2506e990bac6de8ec5e3de34a04f1
        with:
          gradle-version: wrapper
          build-root-directory: packages/server
          arguments: |
            spotlessApply

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: "chore: lint server codebase"
