---
name: Lint Generated Types

# yamllint disable-line rule:truthy
on:
  workflow_call:
  push:
    paths:
      - 'packages/client/hmi-client/src/types/Types.ts'
      - 'packages/server/src/main/java/**'
    branches: ['main']
  pull_request:
    paths:
      - 'packages/client/hmi-client/src/types/Types.ts'
      - 'packages/server/src/main/java/**'
    branches: ['main']
jobs:
  lintTypes:
    name: Lint Generated Types
    runs-on: ubuntu-22.04

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java v17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

      - name: Check Generated Types
        run: ./gradlew generateTypeScript

      - name: Commit all changed files
        uses: stefanzweifel/git-auto-commit-action@4b8a201e31cadd9829df349894b28c54e6c19fe6
        with:
          commit_message: "chore: update generated types"
