---
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests using node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Global File Linting
on:
  workflow_call:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lintYaml:
    name: Lint YAML Files
    uses: darpa-askem/orchestration/.github/workflows/lint-yaml.yml@282c11505705ff017ab58514c951cdf3453159f4
    with:
      strict: false

  lintDocker:
    name: Lint Docker Files
    uses: darpa-askem/orchestration/.github/workflows/lint-docker.yml@282c11505705ff017ab58514c951cdf3453159f4
    with:
      failure-threshold: 'error'
