---
# This workflow will run Spotless with Java configuration to format the Java codebase
name: Lint Server
# yamllint disable-line rule:truthy
on:
  workflow_call:
  push:
    paths:
      - 'packages/server/**'
    branches: [ 'main' ]
  pull_request:
    paths:
      - 'packages/server/**'
    branches: [ 'main' ]

jobs:
  lintServer:
    name: Lint Server
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java v17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Run Spotless
        uses: gradle/gradle-build-action@bdf99f9dada2506e990bac6de8ec5e3de34a04f1
        with:
          gradle-version: wrapper
          build-root-directory: packages/server
          arguments: |
            spotlessApply

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code || echo "Changes detected"

      # Commit changes, only if there are changes
      - name: Commit changes
        if: steps.check_changes.outputs.stdout != ''
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add --all --verbose
          git commit --message "chore: lint server codebase" --verbose
          git push --verbose
