---
name: Lint Generated Types

# yamllint disable-line rule:truthy
on:
  workflow_call:
  pull_request:
    paths:
      - 'packages/client/hmi-client/src/types/Types.ts'
      - 'packages/server/src/main/java/**'
    branches: ['main']
jobs:
  lintTypes:
    name: Lint Generated Types
    runs-on: ubuntu-24.04

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java v17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

      - name: Check Generated Types
        run: ./gradlew generateTypeScript

      - name: Commit all changed files
        run: |
          git diff --exit-code || {
            echo "Files have changed. Committing changes..."
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git fetch --depth=1;
            git checkout  ${{ github.head_ref }} --
            git add .
            git commit --message "chore: lint types"
            git push --set-upstream origin ${{ github.head_ref }}
          }
