---
# Merge AMD64 and ARM64 images into one manifest
name: merge-images.yml

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        description: 'The name of the image to be merged'
        type: string
      image_tag:
        required: true
        description: 'The tag of the image to be merged'
        type: string

jobs:
  merge-images:
    name: Merge into one manifest
    runs-on: ubuntu-22.04
    steps:
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create, inspect and publish manifest
        run: |
          docker manifest create ${{ inputs.image_name }}:${{ inputs.image_tag }} \
            --amend ${{ inputs.image_name }}:${{ inputs.image_tag }}--amd64 \
            --amend ${{ inputs.image_name }}:${{ inputs.image_tag }}--arm64
          docker manifest annotate --arch amd64 --os linux ${{ inputs.image_name }}:${{ inputs.image_tag }} ${{ inputs.image_name }}:${{ inputs.image_tag }}--amd64
          docker manifest annotate --arch arm64 --os linux ${{ inputs.image_name }}:${{ inputs.image_tag }} ${{ inputs.image_name }}:${{ inputs.image_tag }}}--arm64
          docker manifest inspect ${{ inputs.image_name }}:${{ inputs.image_tag }}
          docker manifest push ${{ inputs.image_name }}:${{ inputs.image_tag }}
