# This workflow runs E2E tests using Playwright
#
#   See: https://playwright.dev/

name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    # use docker image of playwright with dependencies
    container:
      image: mcr.microsoft.com/playwright:v1.25.2-jammy
    # Shard the tests across multiple machines to improve performance
    # Can be increased as needed starting with a small pool
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3]
        shardTotal: [3]
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Playwright tests
        # run: yarn workspace client test:e2e --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        run: yarn test:e2e --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - name: Upload test artifacts on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-e2e-report
          # TODO: how to make this a dynamic path?
          path: packages/client/tests/e2e/test-report/
          retention-days: 10

  ct-tests:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    # use docker image of playwright with dependencies
    container:
      image: mcr.microsoft.com/playwright:v1.25.2-jammy
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Playwright tests
        run: yarn test:ct

      - name: Upload test artifacts on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-ct-report
          # TODO: how to make this a dynamic path?
          path: packages/client/tests/component/test-report/
          retention-days: 10
