# This workflow runs E2E tests using Playwright
#
#   See: https://playwright.dev/

name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Use Node v18.8.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.8.0
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: yarn test:e2e

      - name: Upload test artifacts on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-e2e-report
          # TODO: how to make this a dynamic path?
          path: packages/client/tests/e2e/test-report/
          retention-days: 10

  ct-tests:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Use Node v18.8.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.8.0
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: yarn test:ct

      - name: Upload test artifacts on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-ct-report
          # TODO: how to make this a dynamic path?
          path: packages/client/tests/component/test-report/
          retention-days: 10
