---
# Automatically build and publish the server to the container registry.
# This workflow is triggered on changes to the server directory.

name: Build and Publish hmi-server

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - 'packages/server/**'
      - '.github/workflows/**'
    branches:
      - 'main'
      - 'use-mac-os-to-build-arm-images'
    tags:
      - '*'

jobs:
  image-tag:
    name: Get tagged image name
    uses: ./.github/workflows/image-tag.yml
    with:
      image-name: ghcr.io/darpa-askem/hmi-server
