---
# Automatically build and publish the client to the container registry.
# This workflow is triggered on changes to the client directory.

name: Build and Publish hmi-client

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - 'packages/client/**'
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  image-tag:
    name: Get tagged image name
    uses: ./.github/workflows/image-tag.yml
    with:
      image-name: ghcr.io/darpa-askem/hmi-client

  amd64:
    runs-on: ubuntu-22.04
    needs: image-tag
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node 20.10.0 LTS
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Build hmi-client using Makefile
        run: make image-hmi-client

      - name: Create image and push
        uses: docker/build-push-action@v5
        with:
          context: packages/client/hmi-client/docker
          platforms: linux/amd64
          push: true
          tags: ${{ needs.image-tag.outputs.tagged-image-name }}--amd64

  arm64-macos:
    if: false
    # Disabled until macOS GitHub runners uses M2 that can do nested virtualization
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#limitations-for-arm64-macos-runners
    runs-on: macos-14
    needs: image-tag
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Docker on macOS
        uses: douglascamata/setup-docker-macos-action@v1-alpha

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Build hmi-client using Makefile
        run: make image-hmi-client

      - name: Create image and push
        uses: docker/build-push-action@v5
        with:
          context: packages/client/hmi-client/docker
          platforms: linux/arm64
          push: true
          tags: ${{ needs.image-tag.outputs.tagged-image-name }}--arm64

  arm64-emulation:
    runs-on: ubuntu-22.04
    needs: image-tag
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Node 20.10.0 LTS
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Build hmi-client using Makefile
        run: make image-hmi-client

      - name: Create image and push
        uses: docker/build-push-action@v5
        with:
          context: packages/client/hmi-client/docker
          platforms: linux/arm64
          push: true
          tags: ${{ needs.image-tag.outputs.tagged-image-name }}--arm64

  merge-images:
    name: Merge AMD64 and ARM64 images under one manifest
    needs:
      - image-tag
      - amd64
      # - arm64-macos
      - arm64-emulation
    uses: ./.github/workflows/merge-images.yml
    with:
      name: ${{ needs.image-tag.outputs.tagged-image-name }}
