---
# This workflow runs server Unit Tests

name: Server Unit Tests
# yamllint disable-line rule:truthy
on:
  workflow_call:

jobs:
  unit-tests:
    name: Quarkus Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      # Debugging purposes to verify branch being worked on
      - run: git branch

      - name: Setup Java v17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

      - name: Run Unit Tests
        run: ./gradlew test --info
