---
# This workflow tests the HMI Server

name: Server Tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches: ["main"]
    paths:
      - "packages/server/**"
  pull_request:
    branches: ["main"]
    paths:
      - "packages/server/**"
  # Allow for triggering from other workflows
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  server-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Service containers to run with this job
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14.1-alpine
        # Env Variables
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: "panteratest"
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        # Docker Hub image
        image: redis:7-alpine
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    permissions:
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: authzed/action-spicedb@v1
        with:
          version: v1.24.0

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Validate Gradle JAR
      - name: Validate GradleW JAR
        uses: gradle/wrapper-validation-action@342dbebe7272035434f9baccc29a816ec6dd2c7b

      # Setup Java
      - name: Setup Java v17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17

      # Run the tests
      - name: Run tests
        uses: gradle/gradle-build-action@62cce3c597efd445cd71ee868887b8b1117703a7
        with:
          gradle-version: wrapper
          build-root-directory: packages/server
          arguments: |
            test
            --info
