---
# This workflow runs all client tests

name: Client Tests
on:
  workflow_call:
  push:
    paths:
      - 'packages/client/**'
    branches: ['main']
  pull_request:
    paths:
      - 'packages/client/**'
    branches: ['main']

jobs:
  unit-tests:
    name: Client Unit Tests
    uses: ./.github/workflows/test-client-unit.yml

  e2e-tests:
    name: E2E Tests
    uses: ./.github/workflows/test-client-e2e.yml
