---
# This workflow runs client Unit Tests

name: Client Unit Tests
# yamllint disable-line rule:truthy
on:
  workflow_call:
  workflow_dispatch:

jobs:
  unit-tests:
    name: Vitest Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      # Debugging purposes to verify branch being worked on
      - run: git branch

      - name: Use Node.js 20.10.0 LTS
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: 'yarn'

      - name: Install packages
        env:
          YARN_ENABLE_HARDENED_MODE: 0
        run: yarn install --immutable

      - name: Run Unit Tests
        run: yarn test
