---
# This workflow tests the HMI Server

name: Server Tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches: ["main"]
    paths:
      - "packages/server/**"
  pull_request:
    branches: ["main"]
    paths:
      - "packages/server/**"
  # Allow for triggering from other workflows
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  server-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      checks: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Validate Gradle JAR
      - name: Validate GradleW JAR
        uses: gradle/wrapper-validation-action@b231772637bb498f11fdbc86052b6e8a8dc9fc92

      # Setup Java 17
      - name: Setup Java v17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17

      # Start containers
      - name: Start containers
        run: cd containers && docker compose --file docker-compose-actions.yml up --detach --wait

      # Run the tests
      - name: Run tests
        uses: gradle/gradle-build-action@bdf99f9dada2506e990bac6de8ec5e3de34a04f1
        with:
          gradle-version: wrapper
          build-root-directory: packages/server
          arguments: |
            test
            --info

      # Run test reporter
      - name: Test Report
        uses: dorny/test-reporter@v1.7.0
        if: always()
        with:
          name: Server JUnit Tests
          path: packages/server/build/test-results/test/*.xml    # Path to test results
          reporter: java-junit        # Format of test results

      # Stop containers
      - name: Stop containers
        if: always()
        run: cd containers && docker compose --file docker-compose-actions.yml down
